### ISSUE TITLE
how can save timer ? and see it in List in other view ?

### ISSUE THREAD

**Issue by steo92** [ibrahimyilmaz7/SwiftUI-Countdown-Timer#1]
hello, how can I save the data and then view them later in a list where I decide whether to start or stop?

**Comment by ibrahimyilmaz7** [comment]
Do you want to save remainingSeconds?

**Comment by steo92** [comment]
yes, to then view it in another part, and add the start there too

**Comment by ibrahimyilmaz7** [comment]
It's too much out of the scope of this repository. But here are some useful links for you:

- [**Making Apps with Core Data**](https://developer.apple.com/videos/play/wwdc2019/230/)
- [**Getting Started with Core Data Tutorial**](https://www.raywenderlich.com/7569-getting-started-with-core-data-tutorial)
- [**How to combine Core Data and SwiftUI**](https://www.hackingwithswift.com/books/ios-swiftui/how-to-combine-core-data-and-swiftui)

1. You can use CoreData and use CountdownTimer with a save button.
2. Save remaining seconds to your table when save tapped.
3. List these records in a table on another page.
4. When any of the rows tapped start your Countdown page with seconds of row like:

    `CountdownTimerView(seconds: selectedCellData.seconds)`

Maybe you can try something, then ask your question on StackOverflow.
